/**
 * Catalogue cadeaux live AfriWonder — 200+ entrées TikTok-style.
 *
 * Catégories (14) : classic, reaction, music, food, party, african, luxury,
 *                   sport, fantasy, gaming, nature, culture, animals, vip
 * Rarités (5)     : common, rare, epic, legendary, mythic
 *
 * Taux : 1 coin = 5 FCFA (configurable via LIVE_COIN_RATE_XOF)
 * Part créateur : 70% (configurable via LIVE_GIFT_CREATOR_SHARE)
 */
type GiftSeed = {
  name: string;
  icon: string;
  price: number;
  coin_value: number;
  category: string;
  rarity: 'common' | 'rare' | 'epic' | 'legendary' | 'mythic';
  animation_url: string;
};

function g(
  name: string,
  icon: string,
  price: number,
  category: string,
  rarity: GiftSeed['rarity'],
  anim?: string,
): GiftSeed {
  return {
    name,
    icon,
    price,
    coin_value: price,
    category,
    rarity,
    animation_url: anim || `/animations/gifts/${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.json`,
  };
}

export const LIVE_GIFTS_SEED: GiftSeed[] = [
  // ============================================================
  // COMMON — 1-50 coins (5-250 FCFA) — usage massif
  // ============================================================
  g('Rose', '🌹', 1, 'classic', 'common'),
  g('Pétale', '🌸', 2, 'classic', 'common'),
  g('Cœur', '❤️', 3, 'classic', 'common'),
  g('Étoile', '⭐', 5, 'classic', 'common'),
  g('Sparkle', '✨', 5, 'classic', 'common'),
  g('Tournesol', '🌻', 6, 'classic', 'common'),
  g('Café', '☕', 7, 'food', 'common'),
  g('Cupcake', '🧁', 8, 'food', 'common'),
  g('Sourire', '😊', 9, 'reaction', 'common'),
  g('Applaudissements', '👏', 10, 'reaction', 'common'),
  g('Pizza', '🍕', 12, 'food', 'common'),
  g('Donut', '🍩', 13, 'food', 'common'),
  g('Glace', '🍦', 14, 'food', 'common'),
  g('Micro', '🎤', 15, 'music', 'common'),
  g('Bisou', '😘', 16, 'reaction', 'common'),
  g('Frites', '🍟', 17, 'food', 'common'),
  g('Sushi', '🍣', 18, 'food', 'common'),
  g('Pouce', '👍', 19, 'reaction', 'common'),
  g('Note de musique', '🎵', 20, 'music', 'common'),
  g('Burger', '🍔', 21, 'food', 'common'),
  g('Gâteau', '🎂', 22, 'food', 'common'),
  g('Pomme', '🍎', 23, 'food', 'common'),
  g('Cerise', '🍒', 24, 'food', 'common'),
  g('Bière', '🍺', 25, 'food', 'common'),
  g('Banane', '🍌', 26, 'food', 'common'),
  g('Pastèque', '🍉', 27, 'food', 'common'),
  g('Thiéboudienne', '🍛', 28, 'culture', 'common'),
  g('Pop-corn', '🍿', 29, 'food', 'common'),
  g('Bouquet', '💐', 30, 'classic', 'common'),
  g('Cacahuète', '🥜', 31, 'food', 'common'),
  g('Bissap', '🥤', 32, 'culture', 'common'),
  g('Sandwich', '🥪', 33, 'food', 'common'),
  g('Maïs', '🌽', 34, 'food', 'common'),
  g('Football', '⚽', 35, 'sport', 'common'),
  g('Ananas', '🍍', 36, 'food', 'common'),
  g('Citron', '🍋', 37, 'food', 'common'),
  g('Basket', '🏀', 38, 'sport', 'common'),
  g('Avocat', '🥑', 39, 'food', 'common'),
  g('Ballon', '🎈', 40, 'party', 'common'),
  g('Champignon', '🍄', 41, 'food', 'common'),
  g('Cookie', '🍪', 42, 'food', 'common'),
  g('Coquillage', '🐚', 43, 'nature', 'common'),
  g('Trèfle 4', '🍀', 44, 'nature', 'common'),
  g('Manette', '🎮', 45, 'gaming', 'common'),
  g('Œuf', '🥚', 46, 'food', 'common'),
  g('Carotte', '🥕', 47, 'food', 'common'),
  g('Mangue', '🥭', 48, 'culture', 'common'),
  g('Croissant', '🥐', 49, 'food', 'common'),
  g('Djembé', '🥁', 50, 'african', 'common'),

  // ============================================================
  // RARE — 55-300 coins (275-1500 FCFA) — usage moyen
  // ============================================================
  g('Casque VR', '🥽', 55, 'gaming', 'rare'),
  g('Kora', '🎼', 60, 'african', 'rare'),
  g('Balafon', '🎹', 65, 'african', 'rare'),
  g('Boubou', '👘', 70, 'culture', 'rare'),
  g('Masque Dogon', '🎭', 75, 'african', 'rare'),
  g('Soleil', '☀️', 80, 'nature', 'rare'),
  g('Lune', '🌙', 82, 'nature', 'rare'),
  g('Caméra', '📷', 84, 'classic', 'rare'),
  g('Lampe magique', '🪔', 86, 'fantasy', 'rare'),
  g('Cadeau emballé', '🎁', 88, 'classic', 'rare'),
  g('Éclair', '⚡', 90, 'reaction', 'rare'),
  g('Feu', '🔥', 92, 'reaction', 'rare'),
  g('Bombe', '💣', 94, 'reaction', 'rare'),
  g('Boum', '💥', 96, 'reaction', 'rare'),
  g('Médaille bronze', '🥉', 98, 'sport', 'rare'),
  g('Baobab', '🌳', 100, 'african', 'rare'),
  g('Tasse café luxe', '☕', 105, 'food', 'rare'),
  g('Arc-en-ciel', '🌈', 110, 'nature', 'rare'),
  g('Lapin', '🐇', 115, 'animals', 'rare'),
  g('Couronne', '👑', 120, 'luxury', 'rare'),
  g('Chien', '🐶', 125, 'animals', 'rare'),
  g('Chat', '🐱', 128, 'animals', 'rare'),
  g('Médaille argent', '🥈', 130, 'sport', 'rare'),
  g('Souris', '🐭', 132, 'animals', 'rare'),
  g('Singe', '🐵', 135, 'animals', 'rare'),
  g('Loup', '🐺', 138, 'animals', 'rare'),
  g('Tabaski', '🐏', 140, 'culture', 'rare'),
  g('Cheval', '🐴', 142, 'animals', 'rare'),
  g('Ours', '🐻', 145, 'animals', 'rare'),
  g('Panda', '🐼', 147, 'animals', 'rare'),
  g('Diamant', '💎', 150, 'luxury', 'rare'),
  g('Pingouin', '🐧', 152, 'animals', 'rare'),
  g('Hibou', '🦉', 154, 'animals', 'rare'),
  g('Aigle', '🦅', 156, 'animals', 'rare'),
  g('Cygne', '🦢', 158, 'animals', 'rare'),
  g('Tour', '🗼', 160, 'culture', 'rare'),
  g('Pieuvre', '🐙', 162, 'animals', 'rare'),
  g('Poisson tropical', '🐠', 164, 'animals', 'rare'),
  g('Méduse', '🪼', 166, 'animals', 'rare'),
  g('Crabe', '🦀', 168, 'animals', 'rare'),
  g('Crevette', '🦐', 170, 'animals', 'rare'),
  g('Calamar', '🦑', 172, 'animals', 'rare'),
  g('Tortue', '🐢', 175, 'animals', 'rare'),
  g('Serpent', '🐍', 178, 'animals', 'rare'),
  g('Rubis', '♦️', 180, 'luxury', 'rare'),
  g('Gorille', '🦍', 182, 'animals', 'rare'),
  g('Orang-outan', '🦧', 184, 'animals', 'rare'),
  g('Crocodile', '🐊', 186, 'animals', 'rare'),
  g('Hippopotame', '🦛', 188, 'animals', 'rare'),
  g('Rhinocéros', '🦏', 190, 'animals', 'rare'),
  g('Buffle', '🐃', 192, 'animals', 'rare'),
  g('Renard', '🦊', 194, 'animals', 'rare'),
  g('Raton laveur', '🦝', 196, 'animals', 'rare'),
  g('Hérisson', '🦔', 198, 'animals', 'rare'),
  g('Feu d\'artifice', '🎆', 200, 'party', 'rare'),
  g('Confettis', '🎉', 205, 'party', 'rare'),
  g('Verre cocktail', '🍸', 210, 'party', 'rare'),
  g('Cocktail tropical', '🍹', 215, 'party', 'rare'),
  g('Saphir', '🔷', 220, 'luxury', 'rare'),
  g('Émeraude', '💚', 225, 'luxury', 'rare'),
  g('Topaze', '🟡', 230, 'luxury', 'rare'),
  g('Améthyste', '🟣', 235, 'luxury', 'rare'),
  g('Trésor', '💼', 240, 'luxury', 'rare'),
  g('Coffre-fort', '🗄️', 245, 'luxury', 'rare'),
  g('Lion africain', '🦁', 250, 'african', 'rare'),
  g('Cosmos', '🌌', 255, 'fantasy', 'rare'),
  g('Zèbre', '🦓', 260, 'african', 'rare'),
  g('Étoile filante', '🌠', 265, 'fantasy', 'rare'),
  g('Girafe', '🦒', 270, 'african', 'rare'),
  g('Météorite', '☄️', 275, 'fantasy', 'rare'),
  g('Safari', '🚙', 280, 'african', 'rare'),
  g('4x4', '🚗', 285, 'luxury', 'rare'),
  g('Limousine', '🚙', 290, 'luxury', 'rare'),
  g('Bus VIP', '🚐', 295, 'luxury', 'rare'),
  g('Éléphant', '🐘', 300, 'african', 'rare'),

  // ============================================================
  // EPIC — 350-2000 coins (1750-10000 FCFA) — moments forts
  // ============================================================
  g('Volcan', '🌋', 350, 'nature', 'epic'),
  g('Cyclone', '🌀', 380, 'nature', 'epic'),
  g('Trophée or', '🏆', 400, 'sport', 'epic'),
  g('Médaille or', '🥇', 420, 'sport', 'epic'),
  g('Voiture sport', '🚗', 450, 'luxury', 'epic'),
  g('Voiture luxe', '🚘', 480, 'luxury', 'epic'),
  g('Champagne', '🍾', 500, 'luxury', 'epic'),
  g('Cocktail VIP', '🍷', 520, 'luxury', 'epic'),
  g('Hélicoptère', '🚁', 550, 'luxury', 'epic'),
  g('Avion privé', '🛩️', 580, 'luxury', 'epic'),
  g('Yacht', '🛥️', 600, 'luxury', 'epic'),
  g('Voilier', '⛵', 620, 'luxury', 'epic'),
  g('Pyramide', '🔺', 650, 'culture', 'epic'),
  g('Sphinx', '🦁', 680, 'culture', 'epic'),
  g('Tigre', '🐅', 700, 'animals', 'epic'),
  g('Léopard', '🐆', 720, 'animals', 'epic'),
  g('Dragon', '🐉', 750, 'fantasy', 'epic'),
  g('Dragon de feu', '🔥', 780, 'fantasy', 'epic'),
  g('Bague de fiançailles', '💍', 800, 'luxury', 'epic'),
  g('Collier diamant', '📿', 830, 'luxury', 'epic'),
  g('Drapeau Mali', '🇲🇱', 850, 'culture', 'epic'),
  g('Drapeau Sénégal', '🇸🇳', 850, 'culture', 'epic'),
  g('Drapeau Côte d\'Ivoire', '🇨🇮', 850, 'culture', 'epic'),
  g('Drapeau Burkina', '🇧🇫', 850, 'culture', 'epic'),
  g('Drapeau Guinée', '🇬🇳', 850, 'culture', 'epic'),
  g('Drapeau Niger', '🇳🇪', 850, 'culture', 'epic'),
  g('Drapeau Mauritanie', '🇲🇷', 850, 'culture', 'epic'),
  g('Drapeau Togo', '🇹🇬', 850, 'culture', 'epic'),
  g('Drapeau Bénin', '🇧🇯', 850, 'culture', 'epic'),
  g('Cheval blanc', '🐎', 900, 'culture', 'epic'),
  g('Pégase', '🦄', 950, 'fantasy', 'epic'),
  g('Phoenix', '🔥', 1000, 'fantasy', 'epic'),
  g('Phoenix d\'or', '🦅', 1050, 'fantasy', 'epic'),
  g('Tempête', '🌪️', 1100, 'nature', 'epic'),
  g('Comète', '☄️', 1200, 'fantasy', 'epic'),
  g('Pluie d\'étoiles', '💫', 1300, 'fantasy', 'epic'),
  g('Étoile polaire', '⭐', 1400, 'fantasy', 'epic'),
  g('Aurora boréale', '🌌', 1500, 'fantasy', 'epic'),
  g('Galaxie naissante', '🌠', 1600, 'fantasy', 'epic'),
  g('Pluie de roses', '🌺', 1700, 'classic', 'epic'),
  g('Champ de fleurs', '🌷', 1800, 'classic', 'epic'),
  g('Jardin tropical', '🌴', 1900, 'nature', 'epic'),
  g('Princesse', '👸', 2000, 'luxury', 'epic'),

  // ============================================================
  // LEGENDARY — 2200-10000 coins (11000-50000 FCFA) — gros fans
  // ============================================================
  g('Concert privé', '🎙️', 2200, 'music', 'legendary'),
  g('Festival', '🎪', 2400, 'music', 'legendary'),
  g('Château', '🏰', 2500, 'luxury', 'legendary'),
  g('Manoir', '🏘️', 2700, 'luxury', 'legendary'),
  g('Fusée', '🚀', 3000, 'fantasy', 'legendary'),
  g('Navette spatiale', '🛸', 3200, 'fantasy', 'legendary'),
  g('Caravane Sahara', '🐪', 3300, 'african', 'legendary'),
  g('Convoi VIP', '🚓', 3500, 'luxury', 'legendary'),
  g('Île privée', '🏝️', 4000, 'luxury', 'legendary'),
  g('Atoll', '🏖️', 4200, 'luxury', 'legendary'),
  g('Mausolée Tombouctou', '🕌', 4500, 'culture', 'legendary'),
  g('Mosquée Djenné', '🕌', 4700, 'culture', 'legendary'),
  g('Jet privé', '✈️', 5000, 'luxury', 'legendary'),
  g('Hélicoptère VIP', '🚁', 5200, 'luxury', 'legendary'),
  g('Concorde', '🛫', 5500, 'luxury', 'legendary'),
  g('Couronne diamant', '💠', 6000, 'luxury', 'legendary'),
  g('Tiare royale', '👑', 6300, 'luxury', 'legendary'),
  g('Or massif', '🪙', 6500, 'luxury', 'legendary'),
  g('Coffre or', '🏆', 6800, 'luxury', 'legendary'),
  g('Empire Mansa Musa', '👑', 7000, 'culture', 'legendary'),
  g('Trésor de Mali', '💰', 7200, 'culture', 'legendary'),
  g('Palais royal', '🏛️', 7500, 'luxury', 'legendary'),
  g('Temple antique', '🏯', 7800, 'culture', 'legendary'),
  g('Pluie d\'or', '💰', 8500, 'luxury', 'legendary'),
  g('Mine d\'or', '⛏️', 8700, 'luxury', 'legendary'),
  g('Planète', '🪐', 9000, 'fantasy', 'legendary'),
  g('Étoile géante', '🌟', 9300, 'fantasy', 'legendary'),
  g('Soleil noir', '🌑', 9500, 'fantasy', 'legendary'),
  g('Ferrari', '🏎️', 10000, 'luxury', 'legendary'),

  // ============================================================
  // MYTHIC — 12000-100000 coins (60000-500000 FCFA) — Whales/Superfans
  // ============================================================
  g('Lamborghini', '🏎️', 12000, 'vip', 'mythic'),
  g('Bugatti', '🚘', 13500, 'vip', 'mythic'),
  g('Galaxie complète', '🌠', 15000, 'vip', 'mythic'),
  g('Voie lactée', '🌌', 16500, 'vip', 'mythic'),
  g('Royaume africain', '👑', 18000, 'vip', 'mythic'),
  g('Empire continental', '🌍', 20000, 'vip', 'mythic'),
  g('Trône royal', '🎖️', 25000, 'vip', 'mythic'),
  g('Sceptre divin', '🔱', 28000, 'vip', 'mythic'),
  g('Légende vivante', '🔱', 30000, 'vip', 'mythic'),
  g('Dieu africain', '⚡', 35000, 'vip', 'mythic'),
  g('Big Bang', '💥', 40000, 'vip', 'mythic'),
  g('Multivers', '♾️', 45000, 'vip', 'mythic'),
  g('Univers', '♾️', 50000, 'vip', 'mythic'),
  g('Trou noir', '🕳️', 60000, 'vip', 'mythic'),
  g('Création', '✨', 75000, 'vip', 'mythic'),
  g('Au-delà', '🔮', 100000, 'vip', 'mythic'),
];
