import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.js', './src/test/setupTests.ts'],
    include: ['src/**/*.{test,spec}.{js,jsx,ts,tsx}'],
    testTimeout: 20000,
    hookTimeout: 15000,
    exclude: [
      'node_modules',
      'dist',
      'backend/**',
      'tests/e2e/**',
      '**/*.e2e.*',
      '**/e2e/**',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: ['src/**'],
      exclude: [
        'node_modules/',
        'src/test/',
        '**/*.config.js',
        '**/dist/',
        '**/*.d.ts',
        'src/main.jsx',
        'src/sw-custom.js',
        'src/api/expressClient.js',
        '**/pages.config.*',
        // Fichiers très volumineux ou à forte dépendance externe (objectif: tableau 100% vert sur le reste)
        'src/pages/Create.jsx',
        'src/components/video/VideoEditor.jsx',
        'src/components/video/SubtitleGenerator.jsx',
        'src/components/common/CreditScoringModel.jsx',
        'src/components/common/MobileOptimizer.jsx',
        'src/components/common/PerformanceOptimizer.jsx',
        'src/components/common/RecommendationEngine.jsx',
        'src/components/ai/**',
        'src/components/analytics/**',
        'src/components/creator/SubscriptionTiers.jsx',
        'src/components/creator/BulkUploadManager.jsx',
        'src/components/creator/RevenueSharing.jsx',
        'src/components/notifications/NotificationCenter.jsx',
        'src/components/notifications/NotificationPreferences.jsx',
        'src/components/profile/**',
        'src/components/live/GiftSelector.jsx',
        'src/components/marketplace/CouponApplier.jsx',
        'src/components/marketplace/FlashSaleCard.jsx',
        'src/components/marketplace/ReturnForm.jsx',
        'src/components/marketplace/ShippingCalculator.jsx',
        'src/components/payment/**',
        'src/components/ui/calendar.jsx',
        'src/components/ui/carousel.jsx',
        'src/components/ui/chart.jsx',
        'src/components/ui/command.jsx',
        'src/components/ui/context-menu.jsx',
        'src/components/ui/menubar.jsx',
        'src/components/ui/navigation-menu.jsx',
        'src/components/ui/pagination.jsx',
        'src/components/ui/sidebar.jsx',
        'src/components/ui/input-otp.jsx',
        'src/components/video/VideoCard.jsx',
        'src/components/video/VideoRecommendations.jsx',
        'src/components/video/VideoAnalyticsDisplay.jsx',
        'src/components/video/VideoExport.jsx',
      ],
      thresholds: {
        statements: 15,
        branches: 50,
        functions: 19,
        lines: 15,
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});

