/**
 * Chemins relatifs pour `apiClient` (baseURL = `…/api/proxy`).
 * Aligné sur le backend Express partagé — ne pas préfixer `/api` ici.
 */
export const API_ROUTES = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  LOGOUT: '/auth/logout',
  REFRESH: '/auth/refresh',
  ME: '/auth/me',
  GOOGLE_OAUTH: '/auth/google',
  FACEBOOK_OAUTH: '/auth/facebook',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/password/reset',
  TWO_FA_ENABLE: '/auth/2fa/enable',
  TWO_FA_VERIFY: '/auth/2fa/verify',

  FEED: '/feed',

  VIDEOS: '/videos',
  VIDEO_LIKE: (id: string) => `/videos/${id}/like`,
  VIDEO_COMMENT: (id: string) => `/videos/${id}/comment`,
  VIDEO_COMMENTS: (id: string) => `/videos/${id}/comments`,

  LIVES: '/live',
  LIVE_START: '/live/start',
  LIVE_END: (id: string) => `/live/${id}/end`,
  LIVE_GIFT: (id: string) => `/live/${id}/gift`,
  LIVE_REPLAY: (id: string) => `/live/${id}/replay`,
  LIVE_HIGHLIGHTS: (id: string) => `/live/${id}/highlights`,

  PRODUCTS: '/products',
  ORDERS: '/orders',
  CART: '/cart',
  MESSAGES_CONVERSATIONS: '/messages/conversations',
  MESSAGES_SEND: '/messages/send',
  PAYMENTS_STRIPE: '/payments/stripe',
  PAYMENTS_ORANGE: '/payments/orange-money',
  PAYMENTS_WAVE: '/payments/wave',
  PAYMENTS_MTN: '/payments/mobile-money',

  BADGES: '/badges',
  LEADERBOARD: '/leaderboard',
  ACHIEVEMENTS: '/achievements',

  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_ANALYTICS_OVERVIEW: '/admin/analytics/overview',
  ADMIN_ANALYTICS_REALTIME: '/admin/analytics/realtime',
  ADMIN_ANALYTICS_USERS: (period = '7d') => `/admin/analytics/users?period=${encodeURIComponent(period)}`,
  ADMIN_ANALYTICS_REVENUE: (period = '30d') => `/admin/analytics/revenue?period=${encodeURIComponent(period)}`,
  ADMIN_ANALYTICS_CONTENT: (period = '7d') => `/admin/analytics/content?period=${encodeURIComponent(period)}`,
  ADMIN_ANALYTICS_VIEWS_INTEGRITY: (windowDays = 7) =>
    `/admin/analytics/views-integrity?windowDays=${encodeURIComponent(String(windowDays))}`,
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_USERS: '/admin/users',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_TRANSACTIONS: '/admin/transactions',
  ADMIN_WITHDRAWALS: '/admin/withdrawals',
  ADMIN_LIVES_ACTIVE: '/admin/lives/active',
  ADMIN_LIVES_HISTORY: '/admin/lives/history',
  ADMIN_LIVE_TERMINATE: (id: string) => `/admin/lives/${id}/terminate`,
  ADMIN_VERIFICATIONS: '/admin/verifications',
  ADMIN_MONETIZATION_REQUESTS: '/admin/monetization-requests',
  MODERATION_REPORTS: '/moderation/reports',
  MODERATION_REPORT_REVIEW: (id: string) => `/moderation/reports/${id}/review`,
  ADMIN_BROADCAST: '/admin/broadcast-notification',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_MODERATION: '/admin/moderation',
  ADMIN_TRANSACTIONS_EXPORT: '/admin/transactions/export',
  ADMIN_CREATORS: '/admin/creators',

  MOBILE_HEALTH: '/mobile/health',
  MOBILE_APP_VERSION: '/mobile/app-version',
  MOBILE_PUSH_TOKEN: '/mobile/push-token',
  MOBILE_PUSH_TOKEN_DELETE: (token: string) => `/mobile/push-token/${encodeURIComponent(token)}`,
  MOBILE_SYNC: '/mobile/sync',
  MOBILE_DOWNLOAD_URL: (id: string) => `/mobile/videos/${id}/download-url`,
  MOBILE_RESOLVE_DEEPLINK: '/mobile/resolve-deeplink',
  MOBILE_DEVICE_SETTINGS: '/mobile/device-settings',
  MOBILE_ANALYTICS_EVENT: '/mobile/analytics/event',
} as const;
