import { Dimensions, StyleSheet } from 'react-native';
import { Colors, FontSizes, Spacing, BorderRadius } from '../../theme/colors';

const { width } = Dimensions.get('window');

export const liveHubStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: Spacing.xl, paddingVertical: Spacing.lg },
  backBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: FontSizes.xl, fontWeight: 'bold', color: Colors.text },
  goLiveBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#E91E63', paddingHorizontal: Spacing.lg, paddingVertical: Spacing.sm, borderRadius: BorderRadius.pill, gap: 6 },
  goLiveBtnText: { color: '#FFF', fontWeight: 'bold', fontSize: FontSizes.sm },
  feedBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  startSchedBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: Colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: BorderRadius.pill,
    zIndex: 2,
  },
  startSchedBtnText: { color: '#FFF', fontSize: FontSizes.xs, fontWeight: '800' },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.xl, marginTop: Spacing.md, gap: 8 },
  liveDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#FF0000' },
  sectionTitle: { color: Colors.text, fontSize: FontSizes.lg, fontWeight: 'bold' },
  replaysSectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.xl,
    marginTop: Spacing.lg,
    gap: Spacing.sm,
  },
  cleanupBtn: { paddingVertical: 6, paddingHorizontal: 10 },
  cleanupBtnText: { color: Colors.textSecondary, fontSize: FontSizes.xs, fontWeight: '600', textDecorationLine: 'underline' },
  liveScroll: { paddingHorizontal: Spacing.xl, gap: Spacing.md, paddingVertical: Spacing.md },
  liveCard: { width: width * 0.6, height: width * 0.8, borderRadius: BorderRadius.xl, overflow: 'hidden' },
  scheduledCard: { width: width * 0.52, height: width * 0.72, borderRadius: BorderRadius.xl, overflow: 'hidden' },
  scheduledImage: { width: '100%', height: '100%' },
  scheduledOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: Spacing.md },
  scheduledBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(59,130,246,0.9)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    gap: 4,
    marginBottom: 6,
  },
  scheduledBadgeText: { color: '#FFF', fontSize: 10, fontWeight: 'bold' },
  scheduledTitle: { color: '#FFF', fontSize: FontSizes.sm, fontWeight: 'bold' },
  scheduledWhen: { color: 'rgba(255,255,255,0.85)', fontSize: FontSizes.xs, marginTop: 4 },
  liveImage: { width: '100%', height: '100%' },
  liveOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: Spacing.lg },
  liveBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FF0000', alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4, gap: 4, marginBottom: 6 },
  liveBadgeDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#FFF' },
  liveBadgeText: { color: '#FFF', fontSize: 11, fontWeight: 'bold' },
  liveTitle: { color: '#FFF', fontSize: FontSizes.md, fontWeight: 'bold' },
  liveStats: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 4 },
  liveStatText: { color: 'rgba(255,255,255,0.8)', fontSize: FontSizes.xs },
  emptyState: { alignItems: 'center', paddingTop: 60, gap: 12 },
  emptyText: { color: Colors.textSecondary, fontSize: FontSizes.md },
  replayCard: { flexDirection: 'row', paddingHorizontal: Spacing.xl, paddingVertical: Spacing.md, gap: Spacing.md },
  replayThumb: { width: 120, height: 160, borderRadius: BorderRadius.md },
  replayInfo: { flex: 1, justifyContent: 'center', gap: 4 },
  replayTitle: { color: Colors.text, fontSize: FontSizes.md, fontWeight: 'bold' },
  replayMeta: { color: Colors.textSecondary, fontSize: FontSizes.xs },
  replayStats: { flexDirection: 'row', gap: Spacing.lg, marginTop: 4 },
  replayStatItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  replayStatText: { color: Colors.textSecondary, fontSize: FontSizes.xs },
  highlightBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: 'rgba(255,234,167,0.15)', alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, marginTop: 4 },
  highlightBadgeText: { color: '#FFEAA7', fontSize: FontSizes.xs },
});
