import { StyleSheet } from 'react-native';
import { Colors, FontSizes, Spacing, BorderRadius } from '../../theme/colors';

export const replayScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: Spacing.xl, paddingVertical: Spacing.lg },
  backBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: FontSizes.xl, fontWeight: 'bold', color: Colors.text },
  content: { paddingHorizontal: Spacing.xl },
  playerBox: { width: '100%', height: 220, borderRadius: BorderRadius.xl, overflow: 'hidden', backgroundColor: Colors.surface, marginBottom: Spacing.lg },
  playerVideo: { width: '100%', height: '100%' },
  playerImage: { width: '100%', height: '100%' },
  playOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingHorizontal: Spacing.lg,
    gap: Spacing.sm,
  },
  noVodText: { color: 'rgba(255,255,255,0.92)', fontSize: FontSizes.sm, textAlign: 'center', lineHeight: 20 },
  replayBadge: { position: 'absolute', top: 12, left: 12, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.6)', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4, gap: 4 },
  replayBadgeText: { color: '#FFF', fontSize: 11, fontWeight: 'bold' },
  title: { color: Colors.text, fontSize: FontSizes.xl, fontWeight: 'bold' },
  description: { color: Colors.textSecondary, fontSize: FontSizes.md, marginTop: 4 },
  statsRow: { flexDirection: 'row', gap: Spacing.lg, marginTop: Spacing.lg, marginBottom: Spacing.lg },
  stat: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  statText: { color: Colors.textSecondary, fontSize: FontSizes.sm },
  recapBox: { backgroundColor: Colors.surface, borderRadius: BorderRadius.lg, padding: Spacing.lg, marginBottom: Spacing.lg },
  recapLine: { color: Colors.textSecondary, fontSize: FontSizes.sm, marginBottom: 6 },
  replayCommentsBox: { backgroundColor: Colors.surface, borderRadius: BorderRadius.lg, padding: Spacing.lg, marginBottom: Spacing.lg },
  replayHint: { color: Colors.textMuted, fontSize: FontSizes.xs, marginBottom: Spacing.md },
  replayEmpty: { color: Colors.textSecondary, fontSize: FontSizes.sm, marginBottom: Spacing.md },
  replayRow: { marginBottom: Spacing.sm, paddingBottom: Spacing.sm, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: Colors.border },
  replayAuthor: { color: Colors.primary, fontSize: FontSizes.sm, fontWeight: '600' },
  replayMsg: { color: Colors.text, fontSize: FontSizes.sm, marginTop: 2 },
  replayInput: { backgroundColor: Colors.background, borderRadius: BorderRadius.md, padding: Spacing.md, color: Colors.text, fontSize: FontSizes.md, marginTop: Spacing.md },
  replayCount: { color: Colors.textMuted, fontSize: FontSizes.xs, alignSelf: 'flex-end', marginTop: 4 },
  replaySend: { backgroundColor: Colors.primary, borderRadius: BorderRadius.md, padding: Spacing.md, alignItems: 'center', marginTop: Spacing.sm },
  replaySendText: { color: '#FFF', fontWeight: 'bold', fontSize: FontSizes.md },
  clipBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,234,167,0.15)', borderRadius: BorderRadius.md, padding: Spacing.lg, gap: 8 },
  republishBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.primary, borderRadius: BorderRadius.md, padding: Spacing.lg, gap: 8, marginBottom: Spacing.md },
  republishBtnText: { color: '#FFF', fontWeight: 'bold', fontSize: FontSizes.md },
  clipBtnText: { color: '#FFEAA7', fontWeight: 'bold', fontSize: FontSizes.md },
  clipForm: { backgroundColor: Colors.surface, borderRadius: BorderRadius.lg, padding: Spacing.lg, marginTop: Spacing.md },
  clipLabel: { color: Colors.textSecondary, fontSize: FontSizes.sm, marginBottom: 4 },
  clipInput: { backgroundColor: Colors.background, borderRadius: BorderRadius.md, padding: Spacing.md, color: Colors.text, fontSize: FontSizes.md, marginBottom: Spacing.sm },
  clipTimeRow: { flexDirection: 'row', gap: Spacing.md },
  createClipBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFEAA7', borderRadius: BorderRadius.md, padding: Spacing.md, marginTop: Spacing.sm, gap: 6 },
  createClipBtnText: { color: '#000', fontWeight: 'bold' },
  sectionTitle: { color: Colors.text, fontSize: FontSizes.lg, fontWeight: 'bold', marginTop: Spacing.xl, marginBottom: Spacing.md },
  highlightItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: Spacing.md, gap: Spacing.md },
  highlightIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,234,167,0.15)', alignItems: 'center', justifyContent: 'center' },
  highlightTitle: { color: Colors.text, fontWeight: '600' },
  highlightMeta: { color: Colors.textSecondary, fontSize: FontSizes.xs },
  repostBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: Colors.surface, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6, borderWidth: 1, borderColor: Colors.primary },
  repostBtnText: { color: Colors.primary, fontSize: FontSizes.xs, fontWeight: '600' },
});
